blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.bolgHome, name='post'),
    path('search/', views.search, name='search'),
    path('category/<slug:category_slug>/', views.bolgHome, name='posts_by_category'),
    path('<slug:post_slug>/', views.blogPost, name='post_detail'),
    path('postComment', views.postComment, name="postComment"),
    # path('search/', views.search, name='search'),
    # path('services/', views.services, name='services'),
    # path('services/<slug:service_slug>/', views.service_detail, name='service_detail'),
    # path('clients/', views.clients, name='clients'),
    # path('testimonials/', views.testimonials, name='testimonials'),
    # path('transport/', views.transport, name='transport'),
    # path('mission-vision/', views.mission_vision, name='mission_vision'),
    # path('group-of-companies/', views.group_of_companies, name='group_of_companies'),
    # path('our-partners/', views.our_partners, name='partners'),

]

dydevops/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/',include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Account, UserProfile
from django.conf import settings
from django.utils.timezone import now
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
# Create your models here.
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,) 
    
class Category(models.Model):
    sno = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=500, blank=True)
    category_image = models.ImageField(upload_to='category/%Y/%m/%d/', blank=True)
    created_on = models.DateTimeField(default=timezone.now)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['-created_on']
        
    def get_url(self):
            return reverse('posts_by_category', args=[self.slug])    
        
    def __str__(self):
        return self.category_name    

class Post(models.Model):
    sno = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    title_tag = models.CharField(max_length=255, default='Blog Post')
    content = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField(upload_to='blog/%Y/%m/%d/', blank=True)
    # category = models.ManyToManyField('Category', related_name='post')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_featured = models.BooleanField(default=False)
    # author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    author = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    created_on = models.DateTimeField(default=timezone.now)
    updated_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    
    class Meta:
        ordering = ['-created_on']
        
    # def category(self):
    #     return ','.join([str(p) for p in self.post_category.all()])
    
    def get_url(self):
         return reverse('post_detail', args=[self.slug])
     
    def __str__(self):
        return self.title
    
class BlogComment(models.Model):
    sno = models.AutoField(primary_key=True)
    comment =  models.TextField()
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)    
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.comment[0:13] + ".... " + "by " + self.user.username

blog/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from .models import Post,BlogComment,Category
from django.contrib import messages
from blog.templatetags import extras
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
# Create your views here.
# def home(request):
#     return HttpResponse("<h1>This is Home Page Website</h1>")

# def post(request):
#     return HttpResponse("<h1>This is Blog  Page Website</h1>")


def bolgHome(request,category_slug=None):
    categories = None
    allPosts = None
    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        recent_posts = Post.objects.filter(status=1)[0:5]
        allPosts = Post.objects.filter(category=categories, status=1)
        paginator = Paginator(allPosts, 5)
        page = request.GET.get('page')
        paged_posts = paginator.get_page(page)
        # post_count = allPosts.count()
    else:
        # allPosts = Post.objects.filter(status=1).order_by('-created_on')
        recent_posts = Post.objects.filter(status=1)[0:5]
        allPosts = Post.objects.all().filter(status=1).order_by('created_on')
        paginator = Paginator(allPosts, 5)
        page = request.GET.get('page')
        paged_posts = paginator.get_page(page)
    context ={
        'allPosts': paged_posts,
        'recent_posts':recent_posts,
        # 'post_count':post_count,
    }
    return render(request, 'blog/blog-list.html',context)

def blogPost(request, post_slug):
    # single_post = get_object_or_404(Post, slug=post_slug)
    recent_posts = Post.objects.filter(status=1)[0:5]
    post = Post.objects.filter(slug=post_slug).first()
    post.save()
    
    comments = BlogComment.objects.filter(post=post, parent=None).order_by('-created_on')
    replies = BlogComment.objects.filter(post=post).exclude(parent=None)
    replyDict = {}
    for reply in replies:
        if reply.parent.sno not in replyDict.keys():
            replyDict[reply.parent.sno] = [reply]
        else:
            replyDict[reply.parent.sno].append(reply)
            
            
    context ={
            'post': post,
            'recent_posts':recent_posts,
            'comments':comments,
            'user':request.user, 
            'replyDict':replyDict,
        }
    
    return render(request, 'blog/blog-details.html',context)


def search(request):
    if 'keyword' in request.GET:
        query = request.GET['keyword']
        if query:
            allPosts = Post.objects.order_by('-created_on').filter(Q(content__icontains=query) | Q(title__icontains=query))
            recent_posts = Post.objects.filter(status=1)[0:2]
        else: 
           allPosts = Post.objects.filter(status=1).order_by('-created_on')[0:4]  
           recent_posts = Post.objects.filter(status=1)[0:3]  
    context = {
        'allPosts': allPosts,
        'query':query, 
        'recent_posts':recent_posts, 
    }
    return render(request, 'blog/blog-list.html', context)


def postComment(request):
    if request.method=="POST":
        comment = request.POST.get("comment")
        user = request.user
        postSno = request.POST.get("postSno")
        post = Post.objects.get(sno=postSno)
        parentSno = request.POST.get("parentSno")
        if parentSno == "":
            comment = BlogComment(comment=comment, user=user, post=post)
            comment.save()
            messages.success(request, "Your comment has been posted successfully")
    
        
        else:
            parent = BlogComment.objects.get(sno=parentSno)
            comment = BlogComment(comment=comment, user=user, post=post, parent=parent)
            comment.save()
            messages.success(request, "Your reply has been posted successfully")
    return redirect(f"/blog/{post.slug}")

templates/blog/blog-list.html
{% extends 'base.html' %}
{% load static %}
{% comment %} {%block js %}
<script>
let previews = document.getElementsByClassName('preview');
Array.from(previews).forEach((element)=>{
  element.innerHTML = element.innerText;
})

</script>
{%endblock js %} {% endcomment %}
{% block content %}
<!--=       Breadcrumb Area Start      =-->
        <!--=====================================-->

        <div class="edu-breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-inner">
                    <div class="page-title">
                        <h1 class="title">Blog</h1>
                    </div>
                    <ul class="edu-breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                        <li class="separator"><i class="icon-angle-right"></i></li>
                        <li class="breadcrumb-item active" aria-current="page">Blog</li>
                    </ul>
                </div>
            </div>
            <ul class="shape-group">
                <li class="shape-1">
                    <span></span>
                </li>
                <li class="shape-2 scene"><img data-depth="2" src="{% static 'assets/images/about/shape-13.png' %}" alt="shape"></li>
                <li class="shape-3 scene"><img data-depth="-2" src="{% static 'assets/images/about/shape-15.png' %}" alt="shape"></li>
                <li class="shape-4">
                    <span></span>
                </li>
                <li class="shape-5 scene"><img data-depth="2" src="{% static 'assets/images/about/shape-07.png' %}" alt="shape"></li>
            </ul>
        </div>

        <!--=====================================-->
        <!--=        Blog Area Start            =-->
        <!--=====================================-->
        <section class="section-gap-equal">
            <div class="container">
                <div class="row row--30">
                    <div class="col-lg-8">
                        {% if allPosts %}
                        {% for post in allPosts %}
                        <div class="edu-blog blog-style-list" data-sal-delay="150" data-sal="slide-up" data-sal-duration="800">
                            <div class="row">
                                <div class="col-lg-6">
                                <div class="thumbnail">
                                    <a href="{{ post.get_url }}">
                                        <img src="{{ post.image.url }}" alt="Blog Images">
                                    </a>
                                </div>
                                </div>
                                <div class="col-lg-6">
                                <div class="content">
                                    <h5 class="title"><a href="{{ post.get_url }}">{{post.title}}</a></h5>
                                    <ul class="blog-meta">
                                        <li><i class="icon-62"></i>{{post.author}}</li>
                                        <li><i class="icon-27"></i>{{post.created_on|date:'d F, Y'}}</li>
                                    </ul>
                                    <p><div class="preview">{{post.content|safe|truncatechars:100 }}</div></p>
                                    <div class="read-more-btn">
                                        <a class="edu-btn btn-border btn-medium" href="{{ post.get_url }}">Learn More <i class="icon-4"></i></a>
                                    </div>
                                </div>
                              </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        	<div>
                        		<h2 style="text-align: left;">No results found!</h2>
                                <p style="text-align: left;">There were no results matching your search <strong>{{query}}</strong></p>
                                <h2 style="text-align: left;">Suggestions:</h2>
                                <ul>
                                <li>Make sure that all words are spelled correctly.</li>
                                <li>Try different keywords.</li>
                                <li>Try more general keywords.</li>
                                </ul>
                        	</div>
                        {% endif %}

                        {% if allPosts.has_other_pages %}
                        <ul class="edu-pagination top-space-30 justify-content-start">
                            {% if allPosts.has_previous %}
                            <li><a href="?page={{allPosts.previous_page_number}}" aria-label="Previous"><i class="icon-west"></i></a></li>
                            {% else %}
                            <li class="page-item disabled"><a aria-label="Previous"><i class="icon-west"></i></a></li>
                			{% endif %}
                            {% for i in allPosts.paginator.page_range %}
                              {% if allPosts.number == i %}
                            <li class="active"><a href="#">{{i}}</a></li>
                            {% else %}
                            <li><a href="?page={{i}}">{{i}}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% comment %} <li><a href="#">3</a></li>
                            <li class="more-next"><a href="#"></a></li>
                            <li><a href="#">8</a></li> {% endcomment %}
                            {% if allPosts.has_next %}
                            <li><a href="?page={{allPosts.next_page_number}}" aria-label="Next"><i class="icon-east"></i></a></li>
                            {% else %}
                            <li class="disabled"><a aria-label="Next"><i class="icon-east"></i></a></li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </div>
                    <div class="col-lg-4">
                        <div class="edu-blog-sidebar">
                            <!-- Start Single Widget  -->
                            <div class="edu-blog-widget widget-search">
                                <div class="inner">
                                    <h4 class="widget-title">Search</h4>
                                    <div class="content">
                                        <form class="blog-search" action="{% url 'search' %}" method="GET">
                                            {% csrf_token %}
                                            <input type="text" placeholder="Search" name="keyword" value="{{request.GET.keyword}}">
                                            <button class="search-button" type="submit"><i class="icon-2"></i></button>
                                            
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!-- End Single Widget  -->
                            <!-- Start Single Widget  -->
                            <div class="edu-blog-widget widget-latest-post">
                                <div class="inner">
                                    <h4 class="widget-title">Latest Post</h4>
                                    <div class="content latest-post-list">
                                        {% for post in recent_posts %}
                                        <div class="latest-post ">
                                            <div class="thumbnail">
                                                <a href="{{ post.get_url }}">
                                                    <img src="{{ post.image.url }}" alt="Blog Images">
                                                </a>
                                            </div>
                                            <div class="post-content">
                                                <h6 class="title"><a href="{{ post.get_url }}">{{post.title}}</a></h6>
                                                <ul class="blog-meta">
                                                    <li><i class="icon-27"></i>{{post.created_on|date:'d F, Y'}}</li>
                                                </ul>
                                            </div>
                                        </div>
                                          {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <!-- End Single Widget  -->
                            <!-- Start Single Widget  -->
                            <div class="edu-blog-widget widget-categories">
                                <div class="inner">
                                    <h4 class="widget-title">Categories</h4>
                                    <div class="content">
                                        <ul class="category-list">
                                            {% for i in links %}
                                            <li><a href="{{ i.get_url }}">{{ i.category_name }} <span>({{i.post_set.all.count}})</span></a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- End Single Widget  -->
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}        
   

templates/blog/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load extras %}
<!--=       Breadcrumb Area Start      =-->
        <!--=====================================-->

        <div class="edu-breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-inner">
                    <div class="page-title">
                        <h1 class="title">{{post.title}}</h1>
                    </div>
                    <ul class="edu-breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                        <li class="separator"><i class="icon-angle-right"></i></li>
                        <li class="breadcrumb-item"><a href="{% url 'post' %}">Blog</a></li>
                        <li class="separator"><i class="icon-angle-right"></i></li>
                        <li class="breadcrumb-item active" aria-current="page">{{post.title}}</li>
                    </ul>
                </div>
            </div>
            <ul class="shape-group">
                <li class="shape-1">
                    <span></span>
                </li>
                <li class="shape-2 scene"><img data-depth="2" src="{% static 'assets/images/about/shape-13.png' %}" alt="shape"></li>
                <li class="shape-3 scene"><img data-depth="-2" src="{% static 'assets/images/about/shape-15.png' %}" alt="shape"></li>
                <li class="shape-4">
                    <span></span>
                </li>
                <li class="shape-5 scene"><img data-depth="2" src="{% static 'assets/images/about/shape-07.png' %}" alt="shape"></li>
            </ul>
        </div>

<div class="container my-3">
  <!-- sect-heading -->
    {% comment %} <h2>Search Results:<span class="mr-md-auto"><b>{{ post_count }}</b> Post found </span></h2> {% endcomment %}
    {% if posts %}
    {% for post in posts %}
        <div class="row no-gutters border rounded overflow-hidden flex-md-row my-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary">Article by {{post.author}}</strong>
            <h3 class="mb-0">{{post.title}}</h3>
            <div class="mb-1 text-muted">{{post.created_on|date:'d F, Y'}}</div>
            <p class="card-text mb-auto"><div class="preview">{{post.content|safe| truncatechars:300 }}</div></p>
            <div class="my-2">
                <a href="{{ post.get_url }}" role="button" class="btn btn-primary">Continue reading</a>
            </div>
            </div>
          <div class="col-auto d-none d-lg-block">
             </div>
        </div>
      {% endfor %}
      {% else %}
      <h2 style="text-align: left;">No results found!</h2>
      <p style="text-align: left;">There were no results matching your search <strong>{{query}}</strong></p>
      <h2 style="text-align: left;">Suggestions:</h2>
      <ul>
      <li>Make sure that all words are spelled correctly.</li>
      <li>Try different keywords.</li>
      <li>Try more general keywords.</li>
      </ul>  
      {% endif %}
    </div>
    </div>
    {% endblock %} 
                                                